// Font selection, kept in one place so swapping the typeface touches nothing
// else.
//
// Barlow Semi Condensed (Jeremy Tribby, SIL OFL 1.1). The condensed width is
// what makes it a good fit: the clock is limited by how wide two digits are
// on a 200 px panel, and a narrower face converts that slack into height.
//
// Headers are generated by tools/make_fonts.sh and committed. Every font is
// emitted with only the characters it draws.

#pragma once

#include "assets/Strip.h"
#include "assets/TimeBig.h"

// The clock, always two rows. 80x99 px digits.
//
// Black rather than Bold: cap height is fixed at 99 px by the two-row pitch,
// so the only legibility left to gain is stroke mass. Within a family weight
// grows mostly inward, so the widest digit pair is 155 px against a 166 px
// band -- heavier strokes at the same height. Carries '-' for the invalid-time
// face.
#define FONT_TIME (&BarlowSemiCondensed_Black70pt7b)

// Everything in the left strip: month, day, two-letter weekday and battery,
// stacked one glyph per row, all the same size. SemiBold 13pt stretched 1.1x
// horizontally at generation time: 18 px tall (19 double-struck), 3 px
// strokes both ways once double-struck, digits 12 px wide and "W", the
// widest, 20 px -- inside the 23 px strip. Digits plus the letters of SU..SA
// only.
#define FONT_STRIP (&BarlowSemiCondensed_SemiBold13pt7b)
