// Font selection, kept in one place so swapping the typeface touches nothing
// else.
//
// Barlow Semi Condensed (Jeremy Tribby, SIL OFL 1.1). The condensed width is
// what makes it a good fit: the clock is limited by how wide two digits are
// on a 200 px panel, and a narrower face converts that slack into height.
// Black for the clock, SemiBold for the smaller supporting text.
//
// Headers are generated by tools/make_fonts.sh and committed. The time fonts
// are emitted as digits only; the UI font is subset down to the characters
// actually drawn.

#pragma once

#include "assets/TimeBig.h"
#include "assets/Preset.h"
#include "assets/TimeSmall.h"
#include "assets/UI_subset.h"
#include "assets/Weekday.h"

// Two-row clock, when nothing else needs the space. 80x99 px digits.
//
// Black rather than Bold: cap height is fixed at 99 px by the two-row pitch,
// so the only legibility left to gain is stroke mass. Within a family weight
// grows mostly inward, so the widest digit pair is 160 px against a 169 px
// band -- heavier strokes at the same height, for 730 bytes of flash.
#define FONT_TIME_BIG (&BarlowSemiCondensed_Black70pt7b)

// Three-row clock, when a pomodoro row is present. 47x66 px digits. Same
// weight as the two-row face, or the clock would change weight whenever the
// bottom row appeared.
#define FONT_TIME_SMALL (&BarlowSemiCondensed_Black46pt7b)

// Preset row, e.g. "90/20". Its own size because it has to fit four digits
// and a slash in the same band that the timer fills with two digits. 33pt,
// not 36: widening the left strip cut the band to 162 px, and "90/20" at
// 36pt is 168.
#define FONT_PRESET (&BarlowSemiCondensed_Bold33pt7b)

// Weekday, rotated in the left strip. Rotated, a glyph's cap height becomes
// its width and its advance becomes its length, so the size is bounded from
// both directions: 11pt is 17 px wide in the 30 px strip, and its longest
// word ("WED") runs 40 px down it. Going further costs the date and battery
// blocks vertical room they do not have. Uppercase only.
#define FONT_WEEKDAY (&BarlowSemiCondensed_SemiBold11pt7b)

// Date, battery and the NTP message row. To draw a character not
// currently in the subset, add it to tools/subset_font.py first.
#define FONT_UI (&BarlowSemiCondensed_SemiBold13pt7b)
