// Font selection, kept in one place so swapping the typeface touches nothing
// else.
//
// Barlow Semi Condensed (Jeremy Tribby, SIL OFL 1.1). The condensed width is
// what makes it a good fit: the clock is limited by how wide two digits are
// on a 200 px panel, and a narrower face converts that slack into height.
// Bold for the clock, SemiBold for the smaller supporting text.
//
// Headers are generated by tools/make_fonts.sh and committed. The time fonts
// are emitted as digits only; the UI font is subset at build time by
// tools/subset_font.py down to the characters actually drawn.

#pragma once

#include "assets/TimeBig.h"
#include "assets/Preset.h"
#include "assets/TimeSmall.h"
#include "assets/UI_subset.h"
#include "assets/Weekday.h"

// Two-row clock, when nothing else needs the space. 72x99 px digits.
#define FONT_TIME_BIG (&BarlowSemiCondensed_Bold70pt7b)

// Three-row clock, when a pomodoro row is present. 48x65 px digits.
#define FONT_TIME_SMALL (&BarlowSemiCondensed_Bold46pt7b)

// Preset row, e.g. "90/20". Its own size because it has to fit four digits
// and a slash in the same band that the timer fills with two digits.
#define FONT_PRESET (&BarlowSemiCondensed_Bold36pt7b)

// Weekday, rotated in the left strip. Smaller than the rest of the UI text:
// rotated, a glyph's cap height becomes its width, and at the UI size that is
// 20 px against digits only 6-12 px wide -- so it overpowered the column and
// touched both edges. Uppercase only.
#define FONT_WEEKDAY (&BarlowSemiCondensed_SemiBold9pt7b)

// Date, battery and the NTP message row. To draw a character not
// currently in the subset, add it to tools/subset_font.py first.
#define FONT_UI (&BarlowSemiCondensed_SemiBold13pt7b)
